name: 'My Workflow'

on:
  release:
    types: [published]

jobs:
  deploy:
    name: 'Deploy to Netlify'
    steps:
      - uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: -8Y0LKf57WOi73Tqsm3tlFxny-WuSEzhjVlCTIZja0w
          NETLIFY_DEPLOY_TO_PROD: true

